web:
    image: hitalos/laravel:latest
    ports:
        - 80:80
    volumes:
        - ./:/var/www
    working_dir: /var/www
    links:
        - db
    environment:
        DB_HOST: db
        DB_DATABASE: demo_app
        DB_USERNAME: username
        DB_PASSWORD: p445w0rd
        DB_CONNECTION: pgsql

db:
    image: postgres
    environment:
        # with mysql
        # MYSQL_DATABASE: dbname
        # MYSQL_USER: username
        # MYSQL_PASSWORD: p445w0rd

        # with postgres
        POSTGRES_DB: demo_app
        POSTGRES_USER: username
        POSTGRES_PASSWORD: p445w0rd